CREATE TABLE IF NOT EXISTS user_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_id TEXT NOT NULL,
  user_id TEXT,
  input_json TEXT NOT NULL,
  result_json TEXT NOT NULL,

  "1_a" INTEGER NOT NULL DEFAULT 0,
  "1_r" INTEGER NOT NULL DEFAULT 0,
  "1_s" INTEGER NOT NULL DEFAULT 0,
  "2_a" INTEGER NOT NULL DEFAULT 0,
  "2_r" INTEGER NOT NULL DEFAULT 0,
  "2_s" INTEGER NOT NULL DEFAULT 0,
  "3_a" INTEGER NOT NULL DEFAULT 0,
  "3_r" INTEGER NOT NULL DEFAULT 0,
  "3_s" INTEGER NOT NULL DEFAULT 0,

  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_logs_session_id
ON user_logs(session_id);

CREATE INDEX IF NOT EXISTS idx_user_logs_user_id
ON user_logs(user_id);
